---
title: "NYPD"
author: "Priyanka Divi"
date: "2024-02-11"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R NYPD Shooting Incident


```{r NYPD}
options(repos = c(CRAN = "https://cloud.r-project.org"))
if (!require(tidyverse)) {
  install.packages("tidyverse")
}
install.packages("tidyverse")
library(tidyverse)
library(caret)
url_in <- "https://data.cityofnewyork.us/api/views/833y-fsy8/rows.csv?accessType=DOWNLOAD"
nypd <- read_csv(url_in)
nypd
nypd1 <- nypd %>%
      select ( INCIDENT_KEY, OCCUR_DATE, LOCATION_DESC, BORO,STATISTICAL_MURDER_FLAG,PRECINCT, PERP_AGE_GROUP)
nypd1
nypd1$OCCUR_DATE <- as.Date(nypd1$OCCUR_DATE, format = "%m/%d/%Y")
nypd1$year <- format(nypd1$OCCUR_DATE, "%Y")
#Total no of incidents by Year
total_incidents_year <- nypd1 %>%
      group_by(year) %>%
      summarize(total_incidents = n())
total_incidents_year
ggplot(total_incidents_year, aes(x = year, y = total_incidents)) +
      geom_bar(stat = "identity", fill = "skyblue", color = "black") +
      labs(title = "Total Incidents by Year",
      x = "Year",
      y = "Total Incidents") +
      theme_minimal()

#shows the distribution of shootings across different boroughs.
ggplot(nypd, aes(x = BORO)) +
      geom_bar(fill = "skyblue") +
      labs(title = "Distribution of Shootings by Borough", x = "Borough", y = "Number of Shootings")

#Model Visualization
class_counts <- table(nypd1$STATISTICAL_MURDER_FLAG)
class_counts_df <- as.data.frame(class_counts)
names(class_counts_df) <- c("Class", "Count")
bar_plot <- ggplot(class_counts_df, aes(x = Class, y = Count, fill = as.factor(Class))) +
geom_bar(stat = "identity") +
labs(title = "Distribution of STATISTICAL_MURDER_FLAG",
x = "Class",
y = "Count") +
scale_fill_manual(values = c("0" = "skyblue", "1" = "salmon")) +
theme_minimal()
bar_plot
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
